[project]
name = "revolutionary-manager"
authors = ["Your Team"]
description = "A decentralized property management and rental marketplace"
telemetry = false
requirements = []
[contracts.property-exchange]
path = "contracts/property-exchange.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
